name: Deploy to Lambda Feedback

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:


jobs:
  deploy:
    uses: lambda-feedback/evaluation-function-workflows/.github/workflows/deploy.yml@main
    with:
      template-repository-name: 'lambda-feedback/evaluation-function-boilerplate-wolfram'
      build-target: lambda
    secrets:
      aws-key-id: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_ID }}
      aws-secret-key: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_SECRET}}
      function-admin-api-key: ${{ secrets.FUNCTION_ADMIN_API_KEY}}
      build-secrets: |
        "mathpass=${{ secrets.WOLFRAM_ENGINE_MATHPASS }}"
